generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_lichcongtac
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_lichcongtac
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        hoivien_id: {label: Hội viên}
        tieude: {label: Sự kiện}
        noidung: {label: Nội dung}
        start_time: {label: Thời gian bắt đầu}
        end_time: {label: Thời gian kết thúc}
        diadiem: {label: Địa điểm}
      list:
        title: Danh sách lịch công tác
        display: [tieude, noidung, start_time, end_time, diadiem]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: CalendarFilter
        display: [hoivien_id, tieude, start_time]
        fields:
          hoivien_id: {label: Hội viên}
          tieude: {label: Sự kiện}
          start_time: {label: Thời gian bắt đầu}
      form:
        class: CalendarForm
        display: [tieude, noidung, start_time, end_time, diadiem, thanhphan, chuanbi, chutri]
        fields:
          hoivien_id: {label: Hội viên}
          tieude: {label: Sự kiện}
          noidung: {label: Nội dung}
          start_time: {label: Thời gian bắt đầu}
          end_time: {label: Thời gian kết thúc}
          diadiem: {label: Địa điểm}
          thanhphan: {label: Thành phần}
          chuanbi: {label: Chuẩn bị}
          chutri: {label: Chủ trì}
      edit:
        title: Chỉnh sửa lịch công tác
      new:
        title: Tạo mới lịch công tác
