<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('sfCalendar', 'doctrine');

/**
 * BasesfCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $subject
 * @property string $location
 * @property string $description
 * @property timestamp $start_time
 * @property timestamp $end_time
 * @property boolean $is_all_day_event
 * @property string $color
 * @property string $recurring_rule
 * 
 * @method string     getSubject()          Returns the current record's "subject" value
 * @method string     getLocation()         Returns the current record's "location" value
 * @method string     getDescription()      Returns the current record's "description" value
 * @method timestamp  getStartTime()        Returns the current record's "start_time" value
 * @method timestamp  getEndTime()          Returns the current record's "end_time" value
 * @method boolean    getIsAllDayEvent()    Returns the current record's "is_all_day_event" value
 * @method string     getColor()            Returns the current record's "color" value
 * @method string     getRecurringRule()    Returns the current record's "recurring_rule" value
 * @method sfCalendar setSubject()          Sets the current record's "subject" value
 * @method sfCalendar setLocation()         Sets the current record's "location" value
 * @method sfCalendar setDescription()      Sets the current record's "description" value
 * @method sfCalendar setStartTime()        Sets the current record's "start_time" value
 * @method sfCalendar setEndTime()          Sets the current record's "end_time" value
 * @method sfCalendar setIsAllDayEvent()    Sets the current record's "is_all_day_event" value
 * @method sfCalendar setColor()            Sets the current record's "color" value
 * @method sfCalendar setRecurringRule()    Sets the current record's "recurring_rule" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfCalendar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_calendar');
        $this->hasColumn('subject', 'string', 500, array(
             'type' => 'string',
             'comment' => 'Tiêu đề',
             'length' => 500,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Địa điểm',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'Trich dan',
             'length' => 1000,
             ));
        $this->hasColumn('start_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Thoi gian bat dau',
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Thoi gian ket thuc',
             'length' => 25,
             ));
        $this->hasColumn('is_all_day_event', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trang thai',
             ));
        $this->hasColumn('color', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Mau sac',
             'length' => 10,
             ));
        $this->hasColumn('recurring_rule', 'string', 255, array(
             'type' => 'string',
             'comment' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}