<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_giaithuong', 'doctrine');

/**
 * Basecsdl_giaithuong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tengiaithuong
 * @property string $donvitochuc
 * @property integer $namtochuc
 * @property integer $giatri
 * @property string $linhvuc
 * 
 * @method string          getTengiaithuong() Returns the current record's "tengiaithuong" value
 * @method string          getDonvitochuc()   Returns the current record's "donvitochuc" value
 * @method integer         getNamtochuc()     Returns the current record's "namtochuc" value
 * @method integer         getGiatri()        Returns the current record's "giatri" value
 * @method string          getLinhvuc()       Returns the current record's "linhvuc" value
 * @method csdl_giaithuong setTengiaithuong() Sets the current record's "tengiaithuong" value
 * @method csdl_giaithuong setDonvitochuc()   Sets the current record's "donvitochuc" value
 * @method csdl_giaithuong setNamtochuc()     Sets the current record's "namtochuc" value
 * @method csdl_giaithuong setGiatri()        Sets the current record's "giatri" value
 * @method csdl_giaithuong setLinhvuc()       Sets the current record's "linhvuc" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_giaithuong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_giaithuong');
        $this->hasColumn('tengiaithuong', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten giai thuong',
             'length' => 255,
             ));
        $this->hasColumn('donvitochuc', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Don vi to chuc',
             'length' => 255,
             ));
        $this->hasColumn('namtochuc', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'Nam to chuc',
             'length' => 4,
             ));
        $this->hasColumn('giatri', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'gia tri giai thuong',
             'length' => 8,
             ));
        $this->hasColumn('linhvuc', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Linh vuc giai thuong',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}