<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_lylichhoivien', 'doctrine');

/**
 * Basecsdl_lylichhoivien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hoivien_id
 * @property timestamp $ngaysinh
 * @property string $gioitinh
 * @property string $diachi
 * @property string $maquan
 * @property string $matinh
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_lylichhoivien extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_lylich_hoivien');
        $this->hasColumn('hoivien_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'ma hoi vien',
             'length' => 5,
             ));
        $this->hasColumn('ngaysinh', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay sinh cua hoi vien',
             'length' => 25,
             ));
        $this->hasColumn('gioitinh', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Gioi tinh',
             'length' => 25,
             ));
        $this->hasColumn('diachi', 'string', 255, array(
             'type' => 'string',
             'comment' => 'dịa chỉ',
             'length' => 255,
             ));
        $this->hasColumn('maquan', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma quan/huyen',
             'length' => 25,
             ));
        $this->hasColumn('matinh', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ma tinh/thanh pho',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}