<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_nhatky', 'doctrine');

/**
 * Basecsdl_nhatky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hoivien_id
 * @property string $tieude
 * @property string $trichyeu
 * @property clob $noidung
 * @property string $anhdaidien
 * @property boolean $trangthai
 * @property timestamp $ngaytao
 * 
 * @method integer     getHoivienId()  Returns the current record's "hoivien_id" value
 * @method string      getTieude()     Returns the current record's "tieude" value
 * @method string      getTrichyeu()   Returns the current record's "trichyeu" value
 * @method clob        getNoidung()    Returns the current record's "noidung" value
 * @method string      getAnhdaidien() Returns the current record's "anhdaidien" value
 * @method boolean     getTrangthai()  Returns the current record's "trangthai" value
 * @method timestamp   getNgaytao()    Returns the current record's "ngaytao" value
 * @method csdl_nhatky setHoivienId()  Sets the current record's "hoivien_id" value
 * @method csdl_nhatky setTieude()     Sets the current record's "tieude" value
 * @method csdl_nhatky setTrichyeu()   Sets the current record's "trichyeu" value
 * @method csdl_nhatky setNoidung()    Sets the current record's "noidung" value
 * @method csdl_nhatky setAnhdaidien() Sets the current record's "anhdaidien" value
 * @method csdl_nhatky setTrangthai()  Sets the current record's "trangthai" value
 * @method csdl_nhatky setNgaytao()    Sets the current record's "ngaytao" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_nhatky extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_nhatky');
        $this->hasColumn('hoivien_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'ma hoi vien',
             'length' => 5,
             ));
        $this->hasColumn('tieude', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tieu de',
             'length' => 255,
             ));
        $this->hasColumn('trichyeu', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'trich yeu',
             'length' => 1000,
             ));
        $this->hasColumn('noidung', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung bài viết',
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));
        $this->hasColumn('trangthai', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trang thai',
             ));
        $this->hasColumn('ngaytao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay tao',
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}