<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_tacpham', 'doctrine');

/**
 * Basecsdl_tacpham
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tentacpham
 * @property string $gioithieu
 * @property string $anhdaidien
 * @property string $filedownload
 * @property timestamp $ngayxuatban
 * @property string $tacgia
 * 
 * @method string       getTentacpham()   Returns the current record's "tentacpham" value
 * @method string       getGioithieu()    Returns the current record's "gioithieu" value
 * @method string       getAnhdaidien()   Returns the current record's "anhdaidien" value
 * @method string       getFiledownload() Returns the current record's "filedownload" value
 * @method timestamp    getNgayxuatban()  Returns the current record's "ngayxuatban" value
 * @method string       getTacgia()       Returns the current record's "tacgia" value
 * @method csdl_tacpham setTentacpham()   Sets the current record's "tentacpham" value
 * @method csdl_tacpham setGioithieu()    Sets the current record's "gioithieu" value
 * @method csdl_tacpham setAnhdaidien()   Sets the current record's "anhdaidien" value
 * @method csdl_tacpham setFiledownload() Sets the current record's "filedownload" value
 * @method csdl_tacpham setNgayxuatban()  Sets the current record's "ngayxuatban" value
 * @method csdl_tacpham setTacgia()       Sets the current record's "tacgia" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_tacpham extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_tacpham');
        $this->hasColumn('tentacpham', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten tac pham',
             'length' => 255,
             ));
        $this->hasColumn('gioithieu', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'gioi thieu',
             'length' => 1000,
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));
        $this->hasColumn('filedownload', 'string', 255, array(
             'type' => 'string',
             'comment' => 'file download: zip, pdf, doc, docx, xls, xlsx',
             'length' => 255,
             ));
        $this->hasColumn('ngayxuatban', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay xuat ban',
             'length' => 25,
             ));
        $this->hasColumn('tacgia', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tac gia',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}