generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_coquanbanhanh
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_coquanbanhanh
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        madonvi: {label: Mã đơn vị}
        tendonvi: {label: Tên đơn vị}
        gioithieu: {label: Giới thiệu}
        anhdaidien: {label: Ảnh đại diện}
        nguoidaidien: {label: Người đại diện}
        thutu: {label: Thứ tự}
        trangthai: {label: Trạng thái}
      list:
        title: Danh sách cơ quan ban hành
        display: [tendonvi, gioithieu, nguoidaidien, thutu, trangthai]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: CoquanbanhanhFormFilter
        display: [tendonvi]
      form:
        display: [tendonvi, madonvi, nguoidaidien, anhdaidien, gioithieu, thutu, trangthai]
        class: csdlCoQuanBanHanhAdminForm
      edit:
        title: Chỉnh sửa cơ quan ban hành
      new:
        title: Chỉnh sửa cơ quan ban hành
