csdl_loaigiaithuong:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_loaigiaithuong
    module:               csdlLoaigiaithuong
    prefix_path:          /csdlLoaigiaithuong
    column:               id
    with_wildcard_routes: true

csdl_dmnghenghiep:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_dmnghenghiep
    module:               csdlDmNgheNghiep
    prefix_path:          /csdlDmNgheNghiep
    column:               id
    with_wildcard_routes: true

csdl_dantoc:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_dantoc
    module:               csdlDantoc
    prefix_path:          /csdlDantoc
    column:               id
    with_wildcard_routes: true

csdl_chude:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_chude
    module:               csdlChude
    prefix_path:          /csdlChude
    column:               id
    with_wildcard_routes: true

csdl_thehoivien:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_thehoivien
    module:               csdlTheHoiVien
    prefix_path:          /csdlTheHoiVien
    column:               id
    with_wildcard_routes: true

sf_guard_change_password:
  url:   /guard/change_password
  param: { module: sfGuardAuth, action: changePassword }

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /sfGuardGroup
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /sfGuardUser
    column:               id
    with_wildcard_routes: true
 
sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /sfGuardPermission
    column:               id
    with_wildcard_routes: true

vtp_search_ajax_loadarticle:
  url:   /ajax/LoadArticle
  param: { module: ajax, action: loadArticle }

# default rules
homepage:
  url:   /
  param: { module: homePage, action: index }
# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
