csdl_vanbanphapquy:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_vanbanphapquy
    module:               csdlVanbanphapquy
    prefix_path:          /van-ban-phap-quy
    column:               id
    with_wildcard_routes: true

csdl_danhba:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_danhba
    module:               csdlDanhba
    prefix_path:          /danh-ba
    column:               id
    with_wildcard_routes: true

csdl_tacgia:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_tacgia
    module:               csdlTacgia
    prefix_path:          /tac-gia
    column:               id
    with_wildcard_routes: true

csdl_lichcongtac:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_lichcongtac
    module:               csdlLichcongtac
    prefix_path:          /lich-cong-tac
    column:               id
    with_wildcard_routes: true

csdl_tailieunghiepvu:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_tailieunghiepvu
    module:               csdlTailieunghiepvu
    prefix_path:          /tai-lieu-nghiep-vu
    column:               id
    with_wildcard_routes: true

csdl_giaithuong:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_giaithuong
    module:               csdlGiaithuong
    prefix_path:          /giai-thuong
    column:               id
    with_wildcard_routes: true

csdl_nhatky:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_nhatky
    module:               csdlNhatky
    prefix_path:          /nhat-ky
    column:               id
    with_wildcard_routes: true

csdl_tacpham:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_tacpham
    module:               csdlTacpham
    prefix_path:          /tac-pham
    column:               id
    with_wildcard_routes: true

csdl_quatrinhcongtac:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_quatrinhcongtac
    module:               csdlQuatrinhcongtac
    prefix_path:          /qua-trinh-cong-tac
    column:               id
    with_wildcard_routes: true

csdl_lylichhoivien:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_lylichhoivien
    module:               csdlHoivien
    prefix_path:          /hoi-vien
    column:               id
    with_wildcard_routes: true

csdl_coquanbaochi:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_coquanbaochi
    module:               csdlCoQuanBaoChi
    prefix_path:          /co-quan-bao-chi
    column:               id
    with_wildcard_routes: true

csdl_coquanbanhanh:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_coquanbanhanh
    module:               csdlCoQuanBanHanh
    prefix_path:          /co-quan-ban-hanh
    column:               id
    with_wildcard_routes: true

csdl_loaivanban:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_loaivanban
    module:               csdlLoaiVanBan
    prefix_path:          /loai-van-ban
    column:               id
    with_wildcard_routes: true

csdl_loaitailieu:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_loaitailieu
    module:               csdlLoaiTaiLieu
    prefix_path:          /loai-tai-lieu
    column:               id
    with_wildcard_routes: true

csdl_loaigiaithuong:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_loaigiaithuong
    module:               csdlLoaigiaithuong
    prefix_path:          /loai-giai-thuong
    column:               id
    with_wildcard_routes: true

csdl_dmnghenghiep:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_dmnghenghiep
    module:               csdlDmNgheNghiep
    prefix_path:          /danh-muc-nghe-nghiep
    column:               id
    with_wildcard_routes: true

csdl_dantoc:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_dantoc
    module:               csdlDantoc
    prefix_path:          /dan-toc
    column:               id
    with_wildcard_routes: true

csdl_chude:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_chude
    module:               csdlChude
    prefix_path:          /chu-de
    column:               id
    with_wildcard_routes: true

csdl_thehoivien:
  class: sfDoctrineRouteCollection
  options:
    model:                csdl_thehoivien
    module:               csdlTheHoiVien
    prefix_path:          /the-hoi-vien
    column:               id
    with_wildcard_routes: true

sf_guard_change_password:
  url:   /doi-mat-khau
  param: { module: sfGuardAuth, action: changePassword }

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /sfGuardGroup
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /danh-sach-nguoi-dung
    column:               id
    with_wildcard_routes: true
 
sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /danh-sach-quyen
    column:               id
    with_wildcard_routes: true

vtp_search_ajax_loadarticle:
  url:   /ajax/LoadArticle
  param: { module: ajax, action: loadArticle }

# default rules
homepage:
  url:   /trang-chu
  param: { module: homePage, action: index }
# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
