<?php

/**
 * csdl_tacphamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_tacphamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_tacphamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_tacpham');
    }

    public static function getListTacpham($limit=6){
        return csdl_tacphamTable::getInstance()->createQuery()
            ->select('tentacpham, gioithieu, anhdaidien, ngayxuatban, chude_id, tacgia_id')
            ->where('status=2')
            ->orderby('updated_at')
            ->limit($limit)
            ->execute();
    }
}