<?php

/**
 * csdl_quatrinhcongtac
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class csdl_quatrinhcongtac extends Basecsdl_quatrinhcongtac
{
    public function setUp()
    {
        $this->hasMany('csdl_lylichhoivien as csdlHoivien', array(
            'local' => 'hoivien_id',
            'foreign' => 'hoivien_id'));

        $this->hasMany('csdl_coquanbaochi as csdlCoquanbaochi', array(
            'local' => 'donvi_id',
            'foreign' => 'id'));
        parent::setUp();
    }
}