<?php

/**
 * csdl_giaithuongTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_giaithuongTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_giaithuongTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_giaithuong');
    }
}