<?php

/**
 * csdl_chinhtriTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_chinhtriTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_chinhtriTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_chinhtri');
    }
}