<?php

/**
 * csdl_ngoainguTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_ngoainguTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_ngoainguTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_ngoaingu');
    }
}