<?php

/**
 * csdl_tacphamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_tacphamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_tacphamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_tacpham');
    }
}