<?php

/**
 * sfCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfCalendar');
    }
}