generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_lylichhoivien
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_lylichhoivien
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        ten: {label: Tên}
        hodem: {label: Họ và tên}
        ngaysinh: {label: Ngày sinh}
        gioitinh: {label: Giới tính}
        diachi: {label: Quê quán}
        maquan: {label: Quận/huyện}
        matinh: {label: Tỉnh/thành phố}
        tieusu: {label: Tiểu sử}
        nghenghiep_id: {label: Nghề nghiệp}
        dantoc_id: {label: Dân tộc}
        quoctich: {label: Quốc tịch}
        donvi_id: {label: Chi hội}
        dienthoai: {label: Điện thoại}
        email: {label: Email}
        images: {label: Ảnh đại diện}
        hocvan: {label: Học vấn}
        chinhtri: {label: Chính trị}
        ngoaingu: {label: Ngoại ngữ}
        butdanh: {label: Bút danh}
        tacpham_id: {label: Tác phẩm}
        thehnbht: {label: Thẻ HNB Hà Tĩnh}
        giaithuong_id: {label: Khen thưởng/giải thưởng}
        dangvien: {label: Đảng viên}
        cqcongtac: {label: Cơ quan công tác}
        chucvu: {label: Chức vụ hiện tại}
      list:
        title: Danh sách danh hội viên
        display: [images, hodem, ngaysinh, gioitinh]
        object_actions:
          _edit: {label: Sửa}
          _delete: ~
      filter:
#        class: LylichhoivienDaduyetFormFilter
        display: [hodem, ten]
      form:
        display: [hodem, ngaysinh, images, gioitinh, tieusu, nghenghiep_id,donvi_id, dantoc_id, quoctich, matinh, maquan, diachi, dienthoai, email,dangvien, hocvan, chinhtri, ngoaingu, butdanh, thehnbht, , cqcongtac, chucvu]
        class: csdlLyLichHoiVienAdminForm
      edit:
        title: Chỉnh sửa lý lịch hội viên
      new:
        title: Thêm mới lý lịch hội viên
