generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_lylichhoivien
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_lylichhoivien
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        ten: {label: Tên}
        hodem: {label: Họ đệm}
        ngaysinh: {label: Ngày sinh}
        gioitinh: {label: Giới tính}
        diachi: {label: Địa chỉ}
        maquan: {label: Quận/huyện}
        matinh: {label: Tỉnh/thành phố}
        ngayvaodoan: {label: Ngày vào đoàn}
        noiketnapdoan: {label: Nơi kết nạp đoàn}
        ngayvaodang: {label: Ngày vào đảng}
        noiketnapdang: {label: Nơi kết nạp đảng}
        tieusu: {label: Tiểu sử}
        nghenghiep_id: {label: Nghề nghiệp}
        dantoc_id: {label: Dân tộc}
        quoctich: {label: Quốc tịch}
        donvi_id: {label: Đơn vị}
        dienthoai: {label: Điện thoại}
        email: {label: Email}
        images: {label: Ảnh đại diện}
      list:
        title: Danh sách danh hội viên
        display: [hodem, ten, ngaysinh, gioitinh, diachi, maquan, matinh]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: LylichhoivienDaduyetFormFilter
        display: [hodem, ten]
      form:
        display: [ten, hodem, ngaysinh, images, gioitinh,  ngayvaodoan, noiketnapdoan, ngayvaodang, noiketnapdang, tieusu, nghenghiep_id,donvi_id, dantoc_id, quoctich, matinh, maquan, diachi, dienthoai, email]
        class: csdlLyLichHoiVienAdminForm
      edit:
        title: Chỉnh sửa lý lịch hội viên
      new:
        title: Thêm mới lý lịch hội viên
