<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/16 16:49:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=103.27.236.90;dbname=csdl',
  'username' => 'hoinhabao',
  'password' => 'Hnb!23$',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
