<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/16 16:49:51
sfConfig::add(array(
  'app_tmcTwitterBootstrapPlugin_bootstrap_path' => '/tmcTwitterBootstrapPlugin/css/bootstrap.min.css',
  'app_tmcTwitterBootstrapPlugin_responsive_bootstrap_path' => '/tmcTwitterBootstrapPlugin/css/bootstrap-responsive.min.css',
  'app_tmcTwitterBootstrapPlugin_admin_styles_path' => '/tmcTwitterBootstrapPlugin/css/styles.css',
  'app_tmcTwitterBootstrapPlugin_jquery_path' => '/tmcTwitterBootstrapPlugin/js/jquery.min.js',
  'app_tmcTwitterBootstrapPlugin_bootstrap_js_path' => '/tmcTwitterBootstrapPlugin/js/bootstrap.min.js',
  'app_tmcTwitterBootstrapPlugin_admin_js_path' => '/tmcTwitterBootstrapPlugin/js/global.js',
  'app_tmcTwitterBootstrapPlugin_header' => array (
  'menu' => 
  array (
    'Phân hệ Tin tức' => 
    array (
      'credentials' => 
      array (
        0 => 'admin',
      ),
      'dropdown' => 
      array (
        'Quản lý tin đợi duyệt' => 
        array (
          'route' => 'ad_article',
        ),
        'Quản lý tin đợi đăng' => 
        array (
          'route' => 'ad_article_adArticlesAproved',
        ),
        'Quản lý tin đã đăng' => 
        array (
          'route' => 'ad_article_adArticlesPublish',
        ),
      ),
    ),
    'Phân hệ khác' => 
    array (
      'credentials' => 
      array (
        0 => 'admin',
      ),
      'dropdown' => 
      array (
        'Quản lý chuyên mục' => 
        array (
          'route' => 'ad_category',
        ),
        'Trang liên hệ' => 
        array (
          'route' => 'ad_contact',
        ),
        'Quản lý video' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'ad_video',
        ),
        'Quản lý album' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'ad_album',
        ),
        'Quản lý chuyên mục văn bản' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'ad_document_category',
        ),
        'Quản lý văn bản' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'ad_document',
        ),
        'Quản lý nội dung' => 
        array (
          'route' => 'ad_html',
        ),
        'Quản lý thông tin phản hồi' => 
        array (
          'route' => 'ad_comment',
        ),
        'Danh sách hội viên' => 
        array (
          'route' => 'ad_personal',
        ),
        'Vị trí quảng cao' => 
        array (
          'route' => 'ad_advertise_location',
        ),
        'Quản lý Banner - quảng cáo' => 
        array (
          'route' => 'ad_advertise',
        ),
      ),
    ),
    'Quản trị hệ thống' => 
    array (
      'credentials' => 
      array (
        0 => 'admin',
      ),
      'dropdown' => 
      array (
        'Danh sách người dùng' => 
        array (
          'route' => 'sf_guard_user',
        ),
        'Danh sách quyền hạn' => 
        array (
          'route' => 'sf_guard_permission',
        ),
      ),
    ),
  ),
),
  'app_sf_captchagd_image_width' => 180,
  'app_sf_captchagd_image_height' => 27,
  'app_sf_captchagd_charset' => 'ABCDEFGHJKLMNPRSTUXYZabcdefghkmnprstuyz23456789',
  'app_sf_captchagd_code_length_min' => 2,
  'app_sf_captchagd_code_length_max' => 2,
  'app_sf_captchagd_perturbation' => 0.3,
  'app_sf_captchagd_num_lines' => 1,
  'app_sf_captchagd_noise_level' => 2,
  'app_sf_captchagd_use_transparent_text' => true,
  'app_sf_captchagd_text_transparency_percentage' => 10,
  'app_sf_captchagd_image_bg_color' => 'ffffff',
  'app_sf_captchagd_text_color' => 252525,
  'app_sf_captchagd_line_color' => 616161,
  'app_sf_captchagd_chars' => '123456789abcdefghijklmnopqrstuvwxyz',
  'app_sf_captchagd_length' => 2,
  'app_sf_captchagd_font_size' => 14,
  'app_sf_captchagd_force_new_captcha' => true,
  'app_sf_captchagd_fonts' => array (
  0 => 'akbar/vavobi.ttf',
),
  'app_image_maxsize' => 52428800,
  'app_upload_max_size' => 104857600,
  'app_image_upload_max_size' => 52428800,
  'app_upload_video_max_size' => 50485760,
  'app_excel_max_row' => 1000,
  'app_category_images' => 'category_images',
  'app_article_images' => 'article',
  'app_service_images' => 'service',
  'app_advertise_images' => 'advertise',
  'app_product_images' => 'products',
  'app_import_max_size' => 1048576,
  'app_album_images' => 'album',
  'app_video_images' => 'video',
  'app_document' => 'document',
  'app_upload_media_file' => 'E:\\Data_D\\hoi-nha-bao\\website\\web\\uploads',
  'app_url_media_file' => '/uploads',
  'app_url_media_default_file' => 'http://localhost:8086/images/default-image.jpg',
  'app_ckeditor_basePath' => '/js/ckeditor',
  'app_ckfinder_active' => true,
  'app_ckfinder_basePath' => '/js/ckfinder',
  'app_addcslashes_charlist' => '%_-\\\'',
));
