generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_quatrinhcongtac
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_quatrinhcongtac
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        hoivien_id: {label: Hội viên}
        donvi_id: {label: Đơn vị}
        thoigian: {label: Khoảng thời gian}
        batdau: {label: Bắt đầu}
        ketthuc: {label: Kết thúc}
        chucvu: {label: Chức vụ}
        mota: {label: Mô tả công việc}
        noicongtac: {label: Đơn vị công tác}
      list:
        title: Quá trình công tác
        display: [hoivien_id, donvi_id, thoigian, noicongtac, chucvu, mota]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: QuatrinhcongtacFormFilter
        display: [hoivien_id]
      form:
        class: QuatrinhcongtacForm
        display: [hoivien_id, donvi_id, thoigian, noicongtac, chucvu, mota]
      edit:
        title: Chỉnh sửa thông tin
      new:
        title: Thêm mới thông tin