generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_quatrinhcongtac
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_quatrinhcongtac
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        hoivien_id: {label: Mã hội viên}
        donvi_id: {label: Đơn vị công tác}
        thoigian: {label: Số tháng công tác}
        batdau: {label: Thời gian bắt đầu}
        ketthuc: {label: Thời gian kết thúc}
        chucvu: {label: Chức vụ}
        mota: {label: Mô tả}
      list:
        title: Danh sách quá trình công tác
        display: [hoivien_id, donvi_id, batdau, ketthuc, chucvu]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [hoivien_id]
      form:    ~
      edit:    ~
      new:     ~
