generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_giaithuong
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_giaithuong
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        hoivien_id: {label: Hội viên}
        tengiaithuong: {label: Tên giải thưởng}
        madanhmuc: {label: Danh mục}
        namtochuc: {label: Năm tổ chức}
        giatri: {label: Giá trị giải thưởng}
      list:
        title: Danh sách giải thưởng
        display: [tengiaithuong, madanhmuc, namtochuc, giatri ]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: GiaithuongFormFilter
        display: [tengiaithuong, madanhmuc]
      form:
        class: GiaithuongForm
        display: [hoivien_id,tengiaithuong, madanhmuc, namtochuc, giatri ]
      edit:
        title: Chỉnh sửa thông tin giải thưởng
      new:
        title: Tạo mới thông tin giải thưởng
