generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_loaigiaithuong
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_loaigiaithuong
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        madanhmuc: {label: Mã danh mục}
        tendanhmuc: {label: Tên danh mục}
        gioithieu: {label: Giới thiệu}
        anhdaidien: {label: Ảnh đại diện}
        thutu: {label: Thứ tự}
        trangthai: {label: Trạng thái}
      list:
        title: Danh sách danh mục giải thưởng
        display: [tendanhmuc, madanhmuc, gioithieu, thutu, trangthai]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: LoaigiaithuongFormFilter
        display: [tendanhmuc]
      form:
        display: [tendanhmuc, madanhmuc, anhdaidien, gioithieu, thutu, trangthai]
        class: csdlLoaigiaithuongAdminForm
      edit:
        title: Chỉnh sửa danh mục giải thưởng
      new:
        title: Thêm mới danh mục giải thưởng
