generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_nhatky
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_nhatky
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        hoivien_id: {label: Người tác động}
        tieude: {label: Tên chức năng}
        machucnang: {label: Mã chức năng}
        module: {label: Phân hệ}
        ngaytao: {label: Ngày tác động}
        ip: {label: IP server}
      list:
        display: [hoivien_id, tieude, machucnang, module, ngaytao, ip]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
