generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           csdl_tacpham
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          csdl_tacpham
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        anhdaidien: {label: Ảnh đại diện}
        tentacpham: {label: Tên tác phẩm}
        gioithieu: {label: Giới thiệu}
        tacgia_id: {label: Tác giả}
        chude_id: {label: Chủ đề}
        ngayxuatban: {label: Ngày xuất bản}
        filedownload: {label: Tệp đính kèm}
        status: {label: Trạng thái}
        hoivien_id: {label: Hội viên}
      list:
        title: Danh sách tác phẩm
        display: [anhdaidien, tentacpham, tacgia_id, chude_id, ngayxuatban]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        class: TacphamFillters
        display: [tentacpham, tacgia_id, chude_id]
      form:
        class: TacphamForms
        display: [tentacpham, gioithieu, tacgia_id, chude_id, hoivien_id, anhdaidien,filedownload,ngayxuatban,status]
      edit:
        title: Chỉnh sửa tác phẩm
      new:
        title: Tạo mới tác phẩm
